std = "lua51"

max_line_length = 500
unused_args = false

read_globals = {
    -- WoW extends the standard `table` library with wipe(); it is a real global
    -- field on every supported client (28-37 Blizzard call sites per branch).
    -- Preferred over the bare `wipe` global, which is protected on 10.0+.
    table = { fields = { "wipe" } },
    "BackdropTemplateMixin",
    "C_AddOns",
    "C_Item",
    "C_Map",
    "C_NamePlate",
    "C_PaperDollInfo",
    "C_PlayerInfo",
    "C_SpecializationInfo",
    "C_Timer",
    "Enum",
    "TooltipDataProcessor",
    "TooltipUtil",
    "UnitTokenFromGUID",
    "GetAverageItemLevel",
    "GetSpecialization",
    "GetSpecializationInfo",
    "GetSpecializationInfoByID",
    "CANCEL",
    "CanInspect",
    "CastingBarMixin",
    "CharacterModelFrame",
    "CheckInteractDistance",
    "Clamp",
    "ClearAchievementComparisonUnit",
    "CONTAINER_OFFSET_X",
    "CONTAINER_OFFSET_Y",
    "CreateFrame",
    "GetNumTalentGroups",
    "CUSTOM_CLASS_COLORS",
    "DetachTooltip",
    "ERR_INVALID_INSPECT_TARGET",
    "ERR_OUT_OF_RANGE",
    "ERR_UNIT_NOT_FOUND",
    "EventRegistry",
    "GameTooltip",
    "GameTooltipStatusBar",
    "GetAchievementComparisonInfo",
    "GetAchievementInfo",
    "GetActiveTalentGroup",
    "GetAddOnMetadata",
    "GetBestMapForUnit",
    "GetBuildInfo",
    "GetClassAtlas",
    "GetComparisonAchievementPoints",
    "GetComparisonStatistic",
    "GetCursorPosition",
    "GetCVar",
    "GetCVarBool",
    "GetGlyphSocketInfo",
    "GetGuildInfo",
    "GetGuildRosterInfo",
    "GetInventoryItemID",
    "GetInventoryItemLink",
    "GetInventoryItemMixin",
    "GetItemInfo",
    "GetItemInfoInstant",
    "GetLastCacheTime",
    "GetLocale",
    "GetMouseFoci",
    "GetMouseFocus",
    "GetNumGuildMembers",
    "GetNumTalentGroups",
    "GetNumTalents",
    "GetNumTalentsByClass",
    "GetPlayerInfoByGUID",
    "GetQuestDifficultyColor",
    "GetRealmName",
    "GetSpecialization",
    "GetSpecializationName",
    "GetStatistic",
    "GetTalentInfo",
    "GetTalentInfoByClass",
    "GetTalentPoints",
    "GetTime",
    "GetTotalAchievementPoints",
    "GRAY_FONT_COLOR",
    "HIGHLIGHT_FONT_COLOR",
    "hooksecurefunc",
    "InCombatLockdown",
    "InspectFrame",
    "InspectModelFrame",
    "InspectPaperDollFrame",
    "InterfaceOptions_AddCategory",
    "InterfaceOptionsFrame_OpenToCategory",
    "IsEquippableItem",
    "IsGUIDInGroup",
    "IsInGroup",
    "IsInGuild",
    "IsInRaid",
    "IsModifierKeyDown",
    "IsShiftKeyDown",
    "ItemRefTooltip",
    "LE_PARTY_CATEGORY_HOME",
    "LE_PARTY_CATEGORY_INSTANCE",
    "LibSharedMedia",
    "LibStub",
    "LOCALIZED_CLASS_NAMES_MALE",
    "Mixin",
    "MultiBarBottomRight",
    "MultiBarLeft",
    "MultiBarRight",
    "NORMAL_FONT_COLOR",
    "NotifyInspect",
    "PaperDollFrame",
    "PawnClassicLastUpdatedVersion",
    -- Pawn's own registries. PawnCommon.Scales is the exact table Pawn looks a
    -- scale name up in, and PawnScaleProviders holds the registered provider
    -- names; pawn.lua reads both to resolve the library prefix per client without
    -- calling an API that reports an unknown name by printing to chat.
    "PawnCommon",
    "PawnScaleProviders",
    "PawnGetItemData",
    "PawnGetScaleColor",
    "PawnGetSingleValueFromItem",
    "PlayerCastingBarFrame",
    "PowerBarColor",
    "print",
    "RAID_CLASS_COLORS",
    "RequestLoadItemDataByID",
    "RESET",
    "SAVE",
    "select",
    "SetAchievementComparisonUnit",
    "SetCVar",
    "SetPortraitTexture",
    "SetPortraitZoom",
    "Settings",
    "ShoppingTooltip1",
    "ShoppingTooltip2",
    "SlashCmdList",
    "StaticPopupDialogs",
    "StaticPopup_Show",
    "strfind",
    "strlen",
    "strlower",
    "strrep",
    "strreplace",
    "strsub",
    "time",
    "tinsert",
    "tremove",
    "UIDropDownMenu",
    "UIDropDownMenu_AddButton",
    "UIDropDownMenu_CreateInfo",
    "UIDropDownMenu_Initialize",
    "UIDropDownMenu_SetSelectedValue",
    "UIDropDownMenu_SetText",
    "UIParent",
    "UIParentManagedFrameMixin",
    "UIErrorsFrame",
    "UnitCanAttack",
    "UnitClass",
    "UnitClassification",
    "UnitExists",
    "UnitFactionGroup",
    "UnitFrameTarget",
    "UnitGUID",
    "UnitGroupRolesAssigned",
    "UnitInParty",
    "UnitInRaid",
    "UnitIsConnected",
    "UnitIsDeadOrGhost",
    "UnitIsOtherPlayersPet",
    "UnitIsPlayer",
    "UnitIsPVP",
    "UnitIsSameServer",
    "UnitIsUnit",
    "UnitLevel",
    "UnitName",
    "UnitOnTaxi",
    "UnitPower",
    "UnitPowerMax",
    "UnitPowerType",
    "UnitPVPName",
    "UnitRace",
    "unpack",
    "wipe",
    "WorldFrame",
    "AchievementFrame",
    "AchievementFrameComparison",
    "AchievementFrameComparison_OnEvent",
    "APIDocumentation",
    "geterrorhandler",
}

globals = {
    "InspectAvgItemLvl",
    "InspectAvgItemLvlText",
    "InspectGearScore",
    "InspectGearScoreText",
    "PersonalAvgItemLvl",
    "PersonalAvgItemLvlText",
    "PersonalGearScore",
    "PersonalGearScoreText",
    "SLASH_TACOTIP1",
    "SLASH_TACOTIP2",
    "SLASH_TACOTIP3",
    "SLASH_TACOTIP4",
    "SLASH_TACOTIP5",
    "SLASH_TACOTIP6",
    "SLASH_TACOTIP7",
    "TacoTipConfig",
    -- Still used by the Classic addon's pawn.lua at the repo root; TacoTip_Forever
    -- no longer needs it (it resolves the scale library from Pawn's registries).
    "_TacoTipPawnReady",
    "TacoTipDragButton",
    "TacoTipMouseAnchor",
    "TacoTipPowerBar",
    "TacoTip_CustomPosEnable",
    "TacoTip_GSCallback",
    "TACOTIP_LOCALE",
    "TACOTIP_LOCALES",
    "TT_GS",
    "TT_PAWN",
}

files["Locale/*.lua"] = {
    read_globals = {
        "GetLocale",
    },
    globals = {
        "TACOTIP_LOCALE",
        "TACOTIP_LOCALES",
    },
}

files["Libs/LibClassicInspector/LibClassicInspector.lua"] = {
    read_globals = {
        "C_SpecializationInfo",
        "GetActiveTalentGroup",
        "GetNumTalentGroups",
    },
    globals = {},
}

-- Offline verification harnesses. These load the real addon against a mocked
-- WoW environment, so they legitimately touch globals the addon never does.
files["TacoTip_Forever/Tests/harness/*.lua"] = {
    read_globals = {},
    globals = {
        "ERRORS",
        "COLOR_APPLIED",
        "DROPDOWN_SETS",
        "LEGACY_LOG",
        "PICKER_COLOR",
        "PICKER_INFO",
        "SETTINGS_LOG",
        "POSTCALLS",
        "ADDLINE_CALLS",
        "TACO_TIP_DEBUG",
        "TALENTS",
        "TALENT_QUERIES",
        "TALENT_GROUP_POINTS",
        "TALENT_ACTIVE_GROUP",
    },
}
